apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-memory
  #namespace: logeect-stage
  labels:
    app: sysbench-memory
spec:
  template:
    metadata:
      labels:
        app: sysbench-memory
    spec:
      containers:
      - name: fio
        image: homeine/sysbench:latest
        command: ["sh"]
        args: ["-c", "sysbench memory --memory-oper=write --memory-block-size=1K --memory-scope=global --memory-total-size=100G --threads=4 --time=30 run"]
        resources:
          limits:
            memory: 4Gi
        imagePullPolicy: Always
      restartPolicy: Never