---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: fio-job-config-throughput
  #namespace: logeect-stage
  labels:
    app: fio-benchmark-throughput
data:
  fio.job: |-
    [global]
    bs=64K
    iodepth=64
    direct=1
    ioengine=libaio
    group_reporting
    time_based
    runtime=120
    numjobs=4
    name=raw-readwrite
    rw=randrw
    [randreadwrite]
    size=5Gb
    filename=/scratch/job
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-benchmark-throughput
  #namespace: logeect-stage
  labels:
    app: fio-benchmark-throughput
spec:
  template:
    metadata:
      labels:
        app: fio-benchmark-throughput
    spec:
      containers:
      - name: fio
        image: joshuarobinson/fio:3.19
        command: ["sh"]
        args: ["-c", "fio /configs/fio.job"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
        resources:
          limits:
            memory: 4Gi
        imagePullPolicy: Always
      restartPolicy: Never
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config-throughput
      - name: fio-data
        persistentVolumeClaim:
          claimName: fio-claim-throughput
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim-throughput
  #namespace: logeect-stage
  labels:
    app: fio-claim-throughput
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi