apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:11
        env:
        - name: POSTGRES_PASSWORD
          value: supersecret
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 2Gi
        volumeMounts:
          - name: postgresql
            mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgresql-pv
      dnsPolicy: ClusterFirst
      imagePullSecrets:
       - name: registry-kpc-k3s-1-stage-flou
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 25Gi